config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resource :dashboard, only: [:show]
  root 'play#index'
  resources :games, only: [:new, :create, :show, :update, :index] do
    member do
      put :forfeit
      put :stalemate
    end
    resources :pieces, only: [:show, :update]
  end
  get 'about', to: 'games#about'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :pieces
  belongs_to :black_player, class_name: 'User'
  belongs_to :white_player, class_name: 'User'
  belongs_to :active_player, class_name: 'User'
  belongs_to :winning_player, class_name: 'User'

  delegate :pawns, :rooks, :knights, :bishops, :queens, :kings, to: :pieces
  scope :available, -> { where('white_player_id IS NULL OR black_player_id IS NULL AND winning_player_id IS NULL') }

  def populate_board!
    (0..7).each do |i|
      pieces.create(type: 'Pawn', x_position: i, y_position: 1, color: 'white')
    end
    pieces.create(type: 'Rook', x_position: 0, y_position: 0, color: 'white')
    pieces.create(type: 'Rook', x_position: 7, y_position: 0, color: 'white')
    pieces.create(type: 'Knight', x_position: 1, y_position: 0, color: 'white')
    pieces.create(type: 'Knight', x_position: 6, y_position: 0, color: 'white')
    pieces.create(type: 'Bishop', x_position: 2, y_position: 0, color: 'white')
    pieces.create(type: 'Bishop', x_position: 5, y_position: 0, color: 'white')
    pieces.create(type: 'Queen', x_position: 4, y_position: 0, color: 'white')
    pieces.create(type: 'King', x_position: 3, y_position: 0, color: 'white')
    (0..7).each do |i|
      pieces.create(type: 'Pawn', x_position: i, y_position: 6, color: 'black')
    end
    pieces.create(type: 'Rook', x_position: 0, y_position: 7, color: 'black')
    pieces.create(type: 'Rook', x_position: 7, y_position: 7, color: 'black')
    pieces.create(type: 'Knight', x_position: 1, y_position: 7, color: 'black')
    pieces.create(type: 'Knight', x_position: 6, y_position: 7, color: 'black')
    pieces.create(type: 'Bishop', x_position: 2, y_position: 7, color: 'black')
    pieces.create(type: 'Bishop', x_position: 5, y_position: 7, color: 'black')
    pieces.create(type: 'Queen', x_position: 3, y_position: 7, color: 'black')
    pieces.create(type: 'King', x_position: 4, y_position: 7, color: 'black')
  end

  def check?
    white_king = pieces.find_by(type: 'King', color: 'white')
    black_king = pieces.find_by(type: 'King', color: 'black')
    king_in_check?(white_king) || king_in_check?(black_king)
  end

  def stalemate?
    color = active_player == white_player ? 0 : 1
    king = pieces.find_by(type: 'King', color: color) # gets king
    # checks moves
    return false if king_in_check?(king)
    return true unless king_has_valid_move?(king)
    false
  end

  def king_in_check?(king, x = king.x_position, y = king.y_position)
    enemy_pieces = remaining_pieces(opposite_color(king.color)) # creates array of enemy pieces
    enemy_pieces.each do |piece|
      return true if piece.valid_move?(x, y)
    end
    false
  end

  def forfeit(user)
    user.increment(:losses)
    other_user(user).increment(:wins)
    winning_player = other_user(user)
    update!(winning_player: winning_player)
  end

  def assign_turn(player)
    update!(active_player: player)
  end

  private

  def king_has_valid_move?(king)
    (-1..1).each do |x|
      destination_x = king.x_position + x
      (-1..1).each do |y|
        destination_y = king.y_position + y
        return true if king.valid_move?(destination_x, destination_y)
      end
    end
    false
  end

  def remaining_pieces(color) # creates an array of the remaining pieces w/desired color
    pieces.where('color = ? and status = 1', color == 'white' ? 0 : 1).to_a
  end

  def opposite_color(color) # returns the opposite color
    color == 'white' ? 'black' : 'white'
  end

  def other_user(user) # returns the other user
    user == white_player ? black_player : white_player
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def about; end

  def new
    @game = Game.new
  end

  def index
    @available_games = Game.available
  end

  def create
    @game = Game.create(game_params)
    @game.populate_board!

    redirect_to game_path(@game)
  end

  def show
    redirect_to root_path unless user_signed_in?
    @game = Game.find(params[:id])
    @white_player = User.find_by(id: @game.white_player_id) if @game.white_player_id
    @black_player = User.find_by(id: @game.black_player_id) if @game.black_player_id
  end

  def update
    @game = current_game
    @game.update_attributes(game_attributes)
    redirect_to game_path(@game)
  end

  def stalemate
    @game = current_game
    @game.destroy
    redirect_to game_path, alert: 'Stalemate. Game ends in a draw.'
  end

  def forfeit
    @game = current_game
    @game.forfeit(current_user)
    redirect_to game_path, alert: 'You have forfeited.'
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end

  def game_attributes
    params.require(:game).permit(:white_player_id, :black_player_id)
  end

  def current_game
    @game ||= Game.find(params[:id])
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def render_piece(x, y)
    piece = @game.pieces.find_by(x_position: x, y_position: y)
    link_to "#{piece.type} #{piece.color}", game_piece_path(@game, piece) if piece
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end

  # def assign_player_turn
  #   return "White Player's Turn" if @game.swap_active_player == @game.white_player
  #   "Black Player's Turn" if @game.swap_active_player == @game.black_player
  # end

  def whose_turn_text
    return 'Your turn!' if current_user == @game.active_player
    'Not your turn yet.'
  end
end

app/views/games/_board.html.erb
<% (0..7).each do |y| %>
  <div class="row <%= 'top' if y.zero?%> <%= 'bottom' if y == 7 %>">
  <% (0..7).each do |x| %>
    <% if y.even? %>
      <% space_color = x.even? ? 'black' : 'white' %>
    <% else %>
      <% space_color = x.even? ? 'white' : 'black' %>
    <% end %>
    <div class="<%= space_color %> left"
      data-x="<%= x %>"
      data-y="<%= y %>">
        <div class='piece'
          data-x="<%= x %>"
          data-y="<%= y %>">
          <%= render_piece(x,y) %>
        </div>
    </div>
  <% end %>
  </div>
<% end %>

app/views/games/_player_detail.html.erb
<li class="collection-item avatar">
  <%= image_tag avatar_url(player), class: "circle" %>
  <p> <%= color %> Player: <%= player.username %> </p>
  <p> Record: <%= "#{player.wins} - #{player.losses}" %></p>
</li>

app/views/games/about.html.erb
<div id = "hero" class = "center card-panel col s3 white-text formatting">
  <h3 id = "heading">About</h3>
  <div id = "about_text">
    Konquer is a Rails 4 based application where users challenge one another to a game of chess. You can check out the code on <a href= "https://github.com/checkmates1/chess-">GitHub</a>. <br/><br/>It was crafted in an Agile team of five developers under the guidance of <a href = "https://github.com/mscoutermarsh">Mike Coutermarsh</a>, Software Engineer at Product Hunt.Learn more about the developers on their personal GitHub pages:
      <ul class = "center">
        <li><a href = "https://github.com/benzuba11">Ben Zuba</a></li>
        <li><a href = "https://github.com/dasstoni">David Stonikas</a></li>
        <li><a href = "https://github.com/jaredAnders">Jared Gilbert</a></li>
        <li><a href = "https://github.com/rosiehighsmith">Rosie Highsmith</a></li>
        <li><a href = "https://github.com/ryanveroniwooff">Ryan Wooff</a></li>
      </ul>
    We built this app with Test-Driven Development workflow, regularly performed code reviews and pair-programmed to ensure a consistent, well-tested and team-friendly codebase. We hope you enjoy the game!
  </p>
</div>

app/views/games/index.html.erb
<div id = "hero" class = "center card-panel col s3 white-text formatting">
  <h3 id = "heading">Available Games</h3>
  <h4>
    <% @available_games.each do |game| %>
      <% if game.white_player == nil || game.black_player == nil %>
        <li class="game flow-text game-listing">
          <%= link_to "#{game.name ? game.name : 'Game: ' + game.id.to_s} - join now!", game_path(game), class: "teal-text" %>
        </li>
      <% end %>
    <% end %>
  </h4>
  <%= link_to 'New game', new_game_path, class: "waves-effect waves-light btn", id: "index-new-game" %>
</div>

app/views/games/new.html.erb
<div class="card-panel col s3 black white-text formatting">
  <h1>Start a New Game</h1>
    <%= simple_form_for @game do |f| %>
      <div class="field">
      <%= f.input :name, required: true, label: 'Enter a name', error: 'Game MUST have name LESS than 10 characters!', input_html: { maxlength: 10 } %>
      </div>
      <div class="actions">
        <%= f.submit "Start", class: "waves-effect waves-light btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div id = "show_game" class = "center card-panel col s3 white-text formatting">
  <h3><%= @game.name %></h3>

  <% if user_signed_in? %>
    <% if @game.white_player_id == nil %>
      <%= link_to 'Join Game', game_path(@game, game: { white_player_id: current_user.id }), method: :put %>
    <% elsif @game.black_player_id == nil && @game.white_player_id != nil %>
      <% if @game.white_player_id == current_user.id %>
        <p> Waiting for opponent </p>
      <% else %>
        <ul class="collection">
          <%= render "games/player_detail", player: @white_player, color: "White" %>
          <li class="collection-item valign-wrapper">
            <%= link_to 'Join Game', game_path(@game, game: { black_player_id: current_user.id }), class: 'btn btn-flat waves-effect', method: :put %>
          </li>
        </ul>
      <% end %>
    <% else %>
      <ul class="collection">
        <%= render "games/player_detail", player: @white_player, color: "White" %>
        <%= render "games/player_detail", player: @black_player, color: "Black" %>
      </ul>
      <%= link_to 'Try Another Game', root_path %>
    <% end %>
  <% else %>
    <%= link_to 'Sign In To Join', new_user_session_path %>
    <br  />
    <%= link_to 'Sign Up To Join', new_user_registration_path %>
  <% end %>

  <h6><%= link_to 'Return to open games', games_path %></h6>
  <br />

  <% if user_signed_in? %>
    <% if @game.winning_player == nil && @game.white_player_id && @game.black_player_id %>
      <%= link_to 'Forfeit', forfeit_game_path(@game), method: :put %>
    <% end %>
  <% end %>

  <% if (@game.winning_player == nil && @game.white_player_id && @game.black_player_id)  && @game.pieces != []%>
    <% if @game.stalemate? %>
      <%= redirect_to stalemate_game_path(@game), method: :put %>
    <% end %>
  <% end %>
</div>
  <div class="grass valign-wrapper lighten-3">
    <div class="card-panel frame">
      <div class="spacing">
        <%= render "games/board" %>
      </div>
    </div>
  </div>